[book]
authors = ['thinkgo']
language = 'en'
src = 'src'
title = 'Gorm Rapier Documentation'
[output.html]
mathjax-support = true
additional-js = ["resources/prism.js"]
additional-css = ["resources/prism.css"]
git-repository-url = 'https://github.com/thinkgos/gorm-rapier'

[output.html.playground]
editable = true
line-numbers = true

[output.html.fold]
enable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[rust]
edition = '2021'
